### ISSUE TITLE
Question: pdo_pgsql and swoole Postgres

### ISSUE THREAD

**Issue by volodymyr-hordiienko** [hyperf/database-pgsql-incubator#3]
Could you help me with following questions, please? Appreciate any help!
- What is the difference between pdo_pgsql and swoole postgres? 
- What is the best chose?
- Is pdo_pgsql blocking?
- Will this extension be compatitible with hyperf 3.0?
- Are there any plans for stable release?
- Is anywhere exists hyperf docker container with swoole postgres installed?

Postgres is #1 relational db chose for me, it will be very helpfull to have such extension in production, I very appreciate all the hard work you do to make it true!

**Comment by limingxinleo** [comment]
This extension will be compatitible with hyperf 3.0

pdo_pgsql is blocking, so swoole_pgsql is the better selection.

**Comment by limingxinleo** [comment]
SwoolePgSQL will be added into swoole5.0 (may be)
