### ISSUE TITLE
Question: Will this library be ready for 3.0.0?

### ISSUE THREAD

**Issue by volodymyr-hordiienko** [hyperf/database-pgsql-incubator#5]
Perfect news that Swoole 5 is released and more perfect that Pgsql client included in it 🥇 :) I suppose that in near future Hyperf will be also based on Swoole 5, so will this incubator be ready to use soon, or this is far away from production? 

I very impressed by Swoole/Hyperf stack, and in my opinion postgres integration one of most required thing that not completed yet. Thank you for all of the work you do to make it true!

**Comment by limingxinleo** [comment]
It's ready for hyperf 3.0

**Comment by huangzhhui** [comment]
Refer https://github.com/hyperf/hyperf/pull/4994
